import { cx } from "./cx.js";

/**
 * QR code (components/qr-code.md) — a verification QR paired with the human-readable reference number
 * beneath it, so a document is verifiable without a scanner (§9.1). The QR encodes a verification URL
 * or reference only — never sensitive data (§5.6). The image is generated by the app/build (this
 * component takes the produced image src) and its alt text says what scanning does, never "QR code".
 *
 * A build-time generator produces the QR image from the verification URL; this component renders it
 * with the reference below. No client-side QR library is bundled.
 */
interface QrCodeProps {
  /** The generated QR image (data URI or URL). Encodes the verification URL/reference only. */
  src: string;
  /** The same reference in human-readable form, shown beneath and used in the alt text. */
  reference: string;
  /** What scanning does, e.g. "Scan to verify this certificate". */
  alt: string;
  size?: number;
  className?: string;
}

export function QrCode({ src, reference, alt, size = 120, className }: QrCodeProps) {
  return (
    <span className={cx("gov-qr", className)} style={{ display: "inline-flex", flexDirection: "column", alignItems: "center", gap: "var(--gov-space-2)" }}>
      <img src={src} alt={alt} width={size} height={size} style={{ background: "#FFFFFF", padding: "var(--gov-space-2)" }} />
      <code className="gov-reference gov-text-small">{reference}</code>
    </span>
  );
}
